language: php

php:
  - 7.1
  - 7.2

install:
  - composer install --prefer-source

script:
  - php vendor/bin/parallel-lint ./src
  - php vendor/bin/php-cs-fixer fix --config=build/phpcs-fixer.php_cs --dry-run --verbose --diff ./src
  - php vendor/bin/phpcs --standard=rulesetCS.xml --extensions=php --encoding=utf-8 --tab-width=4 -sp ./src
  - php vendor/bin/phpmd ./src text rulesetMD.xml --extensions=php
  - php vendor/bin/phpunit
