language: php

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install --prefer-source

script:
  - vendor/bin/parallel-lint ./src
  - vendor/bin/php-cs-fixer fix --config=build/phpcs-fixer.php_cs --dry-run --verbose --diff ./src
  - vendor/bin/phpcs --standard=rulesetCS.xml --extensions=php --encoding=utf-8 -sp ./src --colors
  - vendor/bin/phpmd ./src text rulesetMD.xml --extensions=php
  - vendor/bin/phpunit
